using System;
namespace Quick_Tasker.Helpers
{
	static class FontAwesomeHelperSolid
	{
        // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
        //Plus is from FASolid
        public const string Plus = "\u002b";
        public const string Bars = "\uf0c9";
        public const string Star = "\u2b50";
        public const string House = "\uf015";
        public const string AlignJustify = "\uf039";
        public const string ListUl = "\uf0ca";
        public const string Trash = "\uf1f8";
        public const string ArrowLeft = "\u2190";
        public const string ArrowRight = "\u2192";
    }
}



