namespace Quick_Tasker.Helpers
{
    static class FontAwesomeHelperSolid
	{
        // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
        //All icons are from FASolid
        public const string ArrowLeft = "\u2190";
        public const string ArrowRight = "\u2192";
    }
}



